apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/twincrafters/oms-user-services:sha-6d3c36d
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: oms-user-service-secret
                  key: DATABASE_URL
            - name: GRPC_PORT
              value: ":50051"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
        - name: inventory-service
          image: ghcr.io/twincrafters/oms-inventory-service:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: oms-inventory-service-secret
                  key: SPRING_DATASOURCE_URL
            - name: GRPC_SERVER_PORT
              value: "9090"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      imagePullSecrets:
        - name: ghcr-login-secret
