kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: oms-user-service-secret
  namespace: oms
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL29tczpvbXNvbXMxMjNAcGdwb29sLXNlcnZpY2UuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL29tcy1kYg==