apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: oms
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: backend-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051