apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: oms
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port:  9090
      targetPort: 9090