apiVersion: v1
kind: Secret
metadata:
  name: oms-inventory-service-secret
  namespace: oms
type: Opaque
data:
  SPRING_DATASOURCE_URL: cG9zdGdyZXNxbDovL29tczpvbXNvbXMxMjNAcGdwb29sLXNlcnZpY2UuY25wZy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL29tcy1kYg==
