name: Bump Dev Manifest Image Version

on:
  workflow_dispatch:
    inputs:
      user-service-tag:
        description: Tag for the manifest to point to
        required: true
        default: latest
        type: string
      inventory-service-tag:
        description: Tag for the manifest to point to
        required: true
        default: latest
        type: string

jobs:
  update-manifest:
    name: Update Manifest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Modify user service manifest
        if: github.event.inputs.user-service-tag != 'latest'
        run: |
          sed -i "s+ghcr.io/twincrafters/oms-user-services.*+ghcr.io/twincrafters/oms-user-services:${{ inputs.user-service-tag }}+g" dev/deployment.yml

      - name: Modify inventory service manifest
        if: github.event.inputs.inventory-service-tag != 'latest'
        run: |
          sed -i "s+ghcr.io/twincrafters/oms-inventory-services.*+ghcr.io/twincrafters/oms-inventory-service:${{ inputs.inventory-service-tag }}+g" dev/deployment.yml

      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(release): bump dev API image version to ${{ inputs.tag }} [skip ci]"

      - name: Push changes
        run: |
          git push https://${{secrets.GH_PAT}}@github.com/TwinCrafters/oms-be-config.git HEAD:main
